name: lauraydaniel_web
description: Web boda Laura & Daniel (Flutter + Appwrite)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  intl: ^0.19.0
  url_launcher: ^6.3.0
  flutter_dotenv: ^5.2.1 # si decides .env (web: compilar con variables)
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  file_picker: ^8.0.3
  http: ^1.2.2
  url_strategy: ^0.3.0
  excel: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
