name: lauraydaniel_web
description: Web boda Laura & Daniel (Flutter + Appwrite)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  file_picker: ^8.0.3
  http: ^1.2.2
  url_strategy: ^0.3.0
  excel: ^4.0.4
  add_2_calendar: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
